### ISSUE TITLE
Can't use StartStep and StopStep in TearDown and SetUp methods

### ISSUE THREAD

**Issue by DarinaKh** [unickq/allure-nunit#4]
Got exceptions: 
For TearDown
Message: TearDown : System.ArgumentNullException : Value cannot be null.
Parameter name: key

For SetUp:
Message: System.ArgumentNullException : Value cannot be null.
Parameter name: key

I use NUnit 3.9.0

**Comment by unickq** [comment]
Please share a code sample or prj if possible

**Comment by DarinaKh** [comment]
@unickq,  sure, here is a screenshot of my code sample
![1519207374287](https://user-images.githubusercontent.com/36265047/36474158-4d85ac58-16ff-11e8-90bf-9fa87e46273b.jpg)

**Comment by unickq** [comment]
I'll check that later.
But it possibly happens because of inability to use setup/teardown with ITestAction.
https://github.com/unickq/allure-nunit/issues/3

What goal are you trying to achieve?

**Comment by DarinaKh** [comment]
@unickq  Thank You for Your response.
I want to display steps from SetUp and TearDown Methods in report.
Please tell me is it possible?

**Comment by unickq** [comment]
@DarinaKh 
No, unfortunately, it's not possible now because of the current implementation of NUnit ITestAction.

**Comment by Noksa** [comment]
@unickq 
Hello! When is the fix expected?
I can not now add an attachment at [TearDown], but TearDown is great place to do that. :(
![error](https://user-images.githubusercontent.com/36312857/39123906-21015546-4702-11e8-91dd-c1c1701866ea.PNG)

**Comment by unickq** [comment]
Fixed https://github.com/unickq/allure-nunit/releases/tag/1.0.0-alfa1

**Comment by Siml1715** [comment]
Hello @unickq,

I appreciate your help. 

I've installed 1.0.3 ver of NUnit.Allure and faced the same issue (System.ArgumentNullException : Value cannot be null). Then I installed 1.0.0 ver but problem was not resolved. I am providing a piece of code:
![image](https://user-images.githubusercontent.com/43149330/45347045-b679a900-b5b3-11e8-9d4e-ad6d183d1a38.png)

Could you please give advice how to resolve this issue?

**Comment by unickq** [comment]
@Siml1715 
You can't use Allure in **OneTimeTearDown**. Allure instance is already disposed.

The execution order is looks like this:
1. [OneTimeSetup]
2. [AllureStart]
3. [SetUp]
4. [Test]
5. [TearDown]
6. [AllureStop]
7. [OneTimeTearDown]

Use **TearDown** for screenshots. The logic is - 1 browser = 1 test. Or you have another structure?
```csharp
var screenshot = ((ITakesScreenshot) Driver).GetScreenshot().AsByteArray;
AllureLifecycle.Instance.AddAttachment("ScreenShot", "image/png", screenshot, ".png");
```

**Comment by Siml1715** [comment]
@unickq

Thank you for advice. Your approach works. I've just shifted screenshot method to TearDown and it worked.

**Comment by unickq** [comment]
@Siml1715 
no prob 😉
